services:

  # CONTAINER 1 — Nginx Proxy Manager (Proxy Reverso com UI)
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80"       # tráfego HTTP da aplicação
      - "443:443"      # HTTPS (opcional)
      - "81:81"         # painel admin do Nginx Proxy Manager
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - apache
    networks:
      - frontend_net

  # CONTAINER 2 — Apache + PHP (Servidor de Aplicação)
  apache:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: apache_php

    volumes:
      - ./www:/var/www/html
      - nfs_uploads:/var/www/html/Public/template/UploadImages
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - frontend_net
      - backend_net

  # CONTAINER 3 — MySQL (Banco de Dados)
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password --sql-mode=""'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: LaborHUB
      MYSQL_USER: aluno
      MYSQL_PASSWORD: "123456"
    ports:
      - "3356:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - backend_net

  # EXTRA — phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_server
    restart: unless-stopped
    ports:
      - "8051:80"
    environment:
      PMA_HOST: mysql_server
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    networks:
      - backend_net

# ── Volumes ──────────────────────────────────────────────
volumes:
  mysql_data:
  npm_data:
  npm_letsencrypt:

  nfs_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nfs/uploads

# ── Redes ────────────────────────────────────────────────
networks:
  frontend_net:
  backend_net: